---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    labels:
      app: hello-openshift
      app.kubernetes.io/component: hello-openshift
      app.kubernetes.io/instance: hello-openshift
    name: hello-openshift
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: hello-openshift
    template:
      metadata:
        labels:
          deployment: hello-openshift
      spec:
        serviceAccountName: test 
        serviceAccount: test 
        containers:
        - image:  <SOME HTTP ROOTLESS HELLO OPENSHIFT APP IMAGE>
          name: hello-openshift
          securityContext:
            privileged: true
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8888
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hello-openshift
      app.kubernetes.io/component: hello-openshift
      app.kubernetes.io/instance: hello-openshift
    name: hello-openshift
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      deployment: hello-openshift
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: test
kind: List
metadata: {}
